/** 30 Qiyas-style demo items: 15 Quantitative, 15 Verbal */

export const seedQuestions = [
  // —— Quantitative (15) ——
  {
    section: "quantitative",
    chapter: "arithmetic",
    difficulty: "easy",
    question_text: "What is 15% of 240?",
    option_a: "32",
    option_b: "36",
    option_c: "40",
    option_d: "45",
    correct_answer: "B",
    explanation:
      "15% = 0.15. Multiply: 0.15 × 240 = 36. Step: 0.1×240=24, 0.05×240=12, 24+12=36.",
  },
  {
    section: "quantitative",
    chapter: "arithmetic",
    difficulty: "medium",
    question_text: "A shirt costs 80 SAR after a 20% discount. What was the original price?",
    option_a: "90 SAR",
    option_b: "96 SAR",
    option_c: "100 SAR",
    option_d: "120 SAR",
    correct_answer: "C",
    explanation:
      "If sale price = 80% of original, then original = 80 / 0.8 = 100 SAR.",
  },
  {
    section: "quantitative",
    chapter: "algebra",
    difficulty: "easy",
    question_text: "Solve for x: 3x - 7 = 14",
    option_a: "5",
    option_b: "6",
    option_c: "7",
    option_d: "8",
    correct_answer: "C",
    explanation: "3x = 21 → x = 7.",
  },
  {
    section: "quantitative",
    chapter: "algebra",
    difficulty: "medium",
    question_text: "If x² - 5x + 6 = 0, what is the sum of the roots?",
    option_a: "3",
    option_b: "4",
    option_c: "5",
    option_d: "6",
    correct_answer: "C",
    explanation: "For ax²+bx+c=0, sum of roots = -b/a. Here 5/1 = 5.",
  },
  {
    section: "quantitative",
    chapter: "geometry",
    difficulty: "medium",
    question_text: "A circle has radius 6. What is its area? (use π as in choice)",
    option_a: "12π",
    option_b: "24π",
    option_c: "36π",
    option_d: "72π",
    correct_answer: "C",
    explanation: "Area = πr² = π·36 = 36π.",
  },
  {
    section: "quantitative",
    chapter: "geometry",
    difficulty: "easy",
    question_text: "In a right triangle, legs are 3 and 4. What is the hypotenuse?",
    option_a: "5",
    option_b: "6",
    option_c: "7",
    option_d: "8",
    correct_answer: "A",
    explanation: "3-4-5 Pythagorean triple: √(3²+4²) = 5.",
  },
  {
    section: "quantitative",
    chapter: "arithmetic",
    difficulty: "hard",
    question_text: "A train travels 45 km in 20 minutes. What is its average speed in km/h?",
    option_a: "120",
    option_b: "125",
    option_c: "130",
    option_d: "135",
    correct_answer: "D",
    explanation: "20 min = 1/3 h. Speed = 45/(1/3) = 135 km/h.",
  },
  {
    section: "quantitative",
    chapter: "algebra",
    difficulty: "hard",
    question_text: "Simplify: 2ˣ = 32. What is x?",
    option_a: "4",
    option_b: "5",
    option_c: "6",
    option_d: "7",
    correct_answer: "B",
    explanation: "32 = 2⁵, so x = 5.",
  },
  {
    section: "quantitative",
    chapter: "arithmetic",
    difficulty: "medium",
    question_text: "The ratio of A to B is 2:3. If A = 10, what is B?",
    option_a: "12",
    option_b: "15",
    option_c: "18",
    option_d: "20",
    correct_answer: "B",
    explanation: "2/3 = 10/B → B = 10×(3/2) = 15.",
  },
  {
    section: "quantitative",
    chapter: "geometry",
    difficulty: "medium",
    question_text: "A rectangle has length 8 and width 5. What is the perimeter?",
    option_a: "20",
    option_b: "26",
    option_c: "32",
    option_d: "40",
    correct_answer: "B",
    explanation: "Perimeter = 2(8+5) = 26.",
  },
  {
    section: "quantitative",
    chapter: "algebra",
    difficulty: "easy",
    question_text: "What is the slope of the line y = 4x - 1?",
    option_a: "1",
    option_b: "4",
    option_c: "-1",
    option_d: "-4",
    correct_answer: "B",
    explanation: "y = mx + b → m = 4.",
  },
  {
    section: "quantitative",
    chapter: "arithmetic",
    difficulty: "easy",
    question_text: "What is 2³ + 3²?",
    option_a: "15",
    option_b: "17",
    option_c: "19",
    option_d: "21",
    correct_answer: "B",
    explanation: "2³=8, 3²=9, sum = 17.",
  },
  {
    section: "quantitative",
    chapter: "geometry",
    difficulty: "hard",
    question_text: "A cube has side length 2. What is the length of the space diagonal?",
    option_a: "2√2",
    option_b: "2√3",
    option_c: "4",
    option_d: "3√2",
    correct_answer: "B",
    explanation: "Space diagonal of cube side a is a√3 = 2√3.",
  },
  {
    section: "quantitative",
    chapter: "algebra",
    difficulty: "medium",
    question_text: "If f(x) = 2x + 1, what is f(3)?",
    option_a: "5",
    option_b: "6",
    option_c: "7",
    option_d: "8",
    correct_answer: "C",
    explanation: "f(3) = 2(3) + 1 = 7.",
  },
  {
    section: "quantitative",
    chapter: "arithmetic",
    difficulty: "medium",
    question_text: "A number is increased by 25% to become 50. What was the number?",
    option_a: "35",
    option_b: "40",
    option_c: "45",
    option_d: "48",
    correct_answer: "B",
    explanation: "N × 1.25 = 50 → N = 50/1.25 = 40.",
  },
  // —— Verbal (15) ——
  {
    section: "verbal",
    chapter: "vocabulary",
    difficulty: "easy",
    question_text: 'Choose the best meaning of "abundant" in: "abundant resources".',
    option_a: "rare",
    option_b: "plentiful",
    option_c: "expensive",
    option_d: "hidden",
    correct_answer: "B",
    explanation: "Abundant means existing in large quantities; plentiful is the best match.",
  },
  {
    section: "verbal",
    chapter: "reading",
    difficulty: "medium",
    question_text:
      "Passage: 'Regular review improves long-term memory.' The author most likely believes that: ",
    option_a: "Cramming is best",
    option_b: "Spaced practice helps retention",
    option_c: "Memory cannot improve",
    option_d: "Exams are unnecessary",
    correct_answer: "B",
    explanation: "Regular review aligns with spaced practice helping retention.",
  },
  {
    section: "verbal",
    chapter: "analogy",
    difficulty: "medium",
    question_text: "Writer : Book  ::  Painter : ?",
    option_a: "Canvas",
    option_b: "Art",
    option_c: "Brush",
    option_d: "Exhibition",
    correct_answer: "B",
    explanation: "A writer creates a book; a painter creates art (work/product).",
  },
  {
    section: "verbal",
    chapter: "vocabulary",
    difficulty: "medium",
    question_text: "أي كلمة أقرب في المعنى لـ «اجتهاد» في سياق الدراسة؟ (Which is closest: diligence)",
    option_a: "كسل",
    option_b: "مثابرة",
    option_c: "ترف",
    option_d: "تأجيل",
    correct_answer: "B",
    explanation: "In study context, اجتهاد (diligence) ≈ مثابرة (perseverance/effort).",
  },
  {
    section: "verbal",
    chapter: "reading",
    difficulty: "easy",
    question_text: "The main idea of a paragraph about 'time management' is usually: ",
    option_a: "Wasting time is good",
    option_b: "Planning use of time improves outcomes",
    option_c: "Schedules are impossible",
    option_d: "Sleep is harmful",
    correct_answer: "B",
    explanation: "Time-management texts support planning to improve results.",
  },
  {
    section: "verbal",
    chapter: "analogy",
    difficulty: "hard",
    question_text: "Clarify : Confusion  ::  Heal : ?",
    option_a: "Medicine",
    option_b: "Wound",
    option_c: "Doctor",
    option_d: "Patient",
    correct_answer: "B",
    explanation: "Clarify removes confusion; heal removes/addresses a wound (problem).",
  },
  {
    section: "verbal",
    chapter: "vocabulary",
    difficulty: "easy",
    question_text: 'Opposite of "diligent" is closest to: ',
    option_a: "lazy",
    option_b: "careful",
    option_c: "proud",
    option_d: "curious",
    correct_answer: "A",
    explanation: "Diligent = hard-working; opposite ≈ lazy.",
  },
  {
    section: "verbal",
    chapter: "reading",
    difficulty: "hard",
    question_text:
      "Text: 'Hypotheses should be testable.' The author would reject: ",
    option_a: "Using experiments",
    option_b: "Claims that cannot be checked",
    option_c: "Data collection",
    option_d: "Clear definitions",
    correct_answer: "B",
    explanation: "Testable means checkable; untestable claims are rejected.",
  },
  {
    section: "verbal",
    chapter: "vocabulary",
    difficulty: "medium",
    question_text: "مترادف (synonym) لـ «دقيق» بمعنى مفصّل:",
    option_a: "واسع",
    option_b: "مفصّل",
    option_c: "سريع",
    option_d: "عام",
    correct_answer: "B",
    explanation: "دقيق meaning detailed is closest to مفصّل.",
  },
  {
    section: "verbal",
    chapter: "analogy",
    difficulty: "easy",
    question_text: "Thermometer : Temperature  ::  Scale : ?",
    option_a: "Weight",
    option_b: "Ruler",
    option_c: "Length",
    option_d: "Volume",
    correct_answer: "A",
    explanation: "Used to measure: thermometer-temperature, scale-weight.",
  },
  {
    section: "verbal",
    chapter: "reading",
    difficulty: "medium",
    question_text: "An inference is best described as: ",
    option_a: "A direct quote",
    option_b: "A logical conclusion from clues",
    option_c: "A random guess",
    option_d: "A spelling error",
    correct_answer: "B",
    explanation: "Inference = conclusion supported by the text, not always stated word-for-word.",
  },
  {
    section: "verbal",
    chapter: "vocabulary",
    difficulty: "hard",
    question_text: "The word 'ambiguous' most nearly means: ",
    option_a: "clear",
    option_b: "open to more than one interpretation",
    option_c: "loud",
    option_d: "permanent",
    correct_answer: "B",
    explanation: "Ambiguous = not clear/uncertain; can be interpreted in multiple ways.",
  },
  {
    section: "verbal",
    chapter: "analogy",
    difficulty: "medium",
    question_text: "Fish : school  ::  Wolf : ?",
    option_a: "pack",
    option_b: "flock",
    option_c: "herd",
    option_d: "pride",
    correct_answer: "A",
    explanation: "A group of fish is a school; a group of wolves is a pack (collective nouns by species).",
  },
  {
    section: "verbal",
    chapter: "reading",
    difficulty: "easy",
    question_text: "A topic sentence usually: ",
    option_a: "Appears in the middle only",
    option_b: "Introduces the main idea of the paragraph",
    option_c: "Is always a question",
    option_d: "Has no function",
    correct_answer: "B",
    explanation: "The topic sentence states the main idea, often at the start.",
  },
  {
    section: "verbal",
    chapter: "vocabulary",
    difficulty: "medium",
    question_text: "مضاد (antonym) لـ «نُدرة» (rarity) في: «ندرة الظروف»",
    option_a: "قلة",
    option_b: "كثرة / شيوع",
    option_c: "جودة",
    option_d: "بطء",
    correct_answer: "B",
    explanation: "نُدرة = rarity; opposite ideas include abundance/شيوع (commonness) depending on collocation — demo answer B.",
  },
];
